### PR TITLE
Create tiny-slider.module.js

### PR DESCRIPTION
**Pull request by tzsk**
this is the fix for the Issue with Webpack module loading with React, i.e. #20 

Now. from a React Component it is to be imported like below:

`import tns from 'tiny-slider/dist/tiny-slider.module'`

And inside the React Component it can be used as the documentation suggested.

Ex:

```js
tns({
    ...
});
```

### CODE REVIEW

**Comment by ganlanyuan** [comment]
Thanks @tzsk ,
May I know the details of the fixing?
1. Change function name from `tns` to `tinySlider`
2. `export default tinySlider` at the end
Right?

So you tried to import "/src/tiny-slider.module.js", and it's not working?

**Comment by tzsk** [comment]
@ganlanyuan Yes. That's exactly the change I've made and it is working now.
I've tested it with [create-react-app](https://github.com/facebookincubator/create-react-app) and [react-webpack-redux](https://github.com/stylesuxx/generator-react-webpack-redux)

But strangely the `/src/tiny-slider.module.js` is not working with any of them.

The thing that is bugging me is that, I've also tested it with `Angular 2/4` and for that, the new file is not working but the old file i.e. `src/tiny-slider.module.js` is working fine.

**Comment by ganlanyuan** [comment]
I see,
Is there any requirement for react to load plugins? Like a config file or
something else.

**Comment by chadspencer** [comment]
Is this PR ready to merge? I would love to have the npm package updated so I can start using the module.

**Comment by ganlanyuan** [comment]
Merge it for now.

**Comment by chadspencer** [comment]
Thanks so much @ganlanyuan. Can you publish the npm package as well?

**Comment by ganlanyuan** [comment]
v1.5.1 was published.

**Comment by tzsk** [comment]
@ganlanyuan Sorry for the late response. But I was looking for other solutions to make it work other than using two separate file for React and Angular 2. And I have found something. In the new way we don't need the new file that I have created. And both Angular 2 and React can use the same file and the API Docs that you wrote in README.md doesn't need to change.

In the new way we can call the file the same way as the docs suggest.
```js
import { tns } from 'tiny-slider/src/tiny-slider.module'
```

I'll post the PR right away.

**Pull request merged**
