### PR TITLE
SSR Proof

### PR DESCRIPTION
**Pull request by glenndeb**
This package will fail when using in a server side rendering application since it is heavily dependent on window and document. I fixed this by adding an "isServer" helper and doing some checks. 

Maybe it is not the cleanest solution but it does the job. Please consider this pull request.

### CODE REVIEW

**Comment by matt3224** [comment]
Can confirm, this works. Tested in Sapper/svelte

**Comment by ganlanyuan** [comment]
I can see you set `window`, `document`, … to `null` if it's server. 
What suppose to do on server side if these are `null`?

**Comment by romanown** [comment]
server side have not windows. if SSR all visibles elements not have windows and window is null. it is bypass.

**Comment by romanown** [comment]
i replaced files from this commit but window is not defined is also.

**Comment by romanown** [comment]
but tns is not a function. how can i import tiny-slider into react app?

**Comment by amanpatel** [comment]
Why was this closed? We are converting our app to SSR and tiny-slider is the only dependency that is giving us a few errors.

**Pull request closed without merging**
