### PR TITLE
Check if event is cancelable before calling preventDefault

### PR DESCRIPTION
**Pull request by mac9416**
This uses MDN's recommendation to avoid preventDefault when it shouldn't be used:
https://developer.mozilla.org/en-US/docs/Web/API/Event/cancelable

Sorry for the messy diff. I think Docker made the whitespace changes? Let me know if you'd like me to clean it up and submit another PR.

### CODE REVIEW

**Comment by mac9416** [comment]
Just discovered this [doesn't completely clean up the console](https://github.com/WICG/interventions/issues/63#issuecomment-449752089). But I think it's a step in the right direction.

**Comment by FlorianKoerner** [comment]
Clean Diff: https://github.com/ganlanyuan/tiny-slider/pull/357/files?utf8=%E2%9C%93&diff=split&w=1

**Comment by eric-blue** [comment]
> Clean Diff: https://github.com/ganlanyuan/tiny-slider/pull/357/files?utf8=%E2%9C%93&diff=split&w=1

Can we have this merged?

**Comment by Eduruiz** [comment]
This solves the issue for me.

**Comment by FredericBriolet** [comment]
Adding `preventScrollOnTouch: 'auto'` to the slider's constructor removed preventDefault errors for me

**Comment by SuperSchek** [comment]
+1. Could really use this fix.

**Comment by mac9416** [comment]
I'm not sure how to resolve this. Since these are built files, should I just choose my version? Super difficult to read the diff.

**Comment by drjgray** [comment]
Any update on this issue?

**Comment by artilishes** [comment]
Any news on this issue?

**Comment by demyan1411** [comment]
?

**Comment by savchukm** [comment]
@mac9416 Could you please clean clean up code changes? I hope it gets merged soon.

**Comment by panec** [comment]
Updated PR: https://github.com/ganlanyuan/tiny-slider/pull/437

**Pull request merged**
