### PR TITLE
Styles from a slide as *

### PR DESCRIPTION
**Pull request by vladimirschneider**

### CODE REVIEW

**Comment by ganlanyuan** [comment]
Hey, I don't like to use the selector `*` due to its inefficiency.
If you prefer to use other tags rather than `div` and `li`, I can add them in the styles.

**Comment by vladimirschneider** [comment]
Can it be better to use a class selector instead of div and li?

**Comment by ganlanyuan** [comment]
Then you have to add the class to each single slide.
I don't want to add this burden to everyone who use the slider.

**Comment by vladimirschneider** [comment]
Well, can you add tag article?

**Comment by ganlanyuan** [comment]
Added in [here](https://github.com/ganlanyuan/tiny-slider/commit/8437ba953ec1d5831004baf0bcdcc57f2cb554d7).

**Comment by ganlanyuan** [comment]
Sorry, I just noticed the selectors was unconsciously changed to `<div>` and `<li>` in one commit. They're switched back to `.tns-item` in the latest commit. You can use any tag as slide from next release.

**Comment by vladimirschneider** [comment]
Thanks you

**Comment by ganlanyuan** [comment]
Published in v2.8.6

**Pull request closed without merging**
