### PR TITLE
Add amount of next/prev slides to preload lazy images in.

### PR DESCRIPTION
**Pull request by sun-ks**

### CODE REVIEW

**Comment by gggritso** [comment]
This is really great! @sun-ks are you able to resolve the conflict on this PR? Would love to see it merged!

**Comment by rolecs** [comment]
lazyLoadEager for Tiny Slider 2

**Comment by kilianso** [comment]
Any update on this? This would be an very useful feature!

**Comment by Simtwo** [comment]
Just tested it ! Amazing !
One more thing would be nice to implement here :
that when you load the page, it could preload the first next image (as it is now) AND the first image BEFORE. So that everything run smoothly. Could it be possible to implement that ?

**Review by ncamaa — COMMENTED** [review]
Works Great.

**Comment by logiqone** [comment]
Two years have passed. The PR of the killer feature is still open. Why? @ganlanyuan

**Comment by baesek** [comment]
I want to use the feature of lazy preloading previous and next slides, but the files in the dist folder of the repository 
[https://github.com/sun-ks/tiny-slider](https://github.com/sun-ks/tiny-slider) are not the files in the src folder processed by gulp. I tried to use docker ( i never used it before ) as described here : https://github.com/ganlanyuan/tiny-slider/blob/master/CONTRIBUTING.md

But when i modify a file to trigger the gulp watch tasks I get the following errors:
`tiny-slider | [Browsersync] Serving files from: ./
tiny-slider | [12:01:56] Starting 'makeDevCopy'...
tiny-slider | [12:01:56] Starting 'script'...
tiny-slider | [12:01:56] 'script' errored after 53 ms
tiny-slider | [12:01:56] Error: Unexpected token
tiny-slider |     at error (/tmp/node_modules/rollup/dist/rollup.js:199:15)
tiny-slider |     at Module.error (/tmp/node_modules/rollup/dist/rollup.js:17179:9)
tiny-slider |     at tryParse (/tmp/node_modules/rollup/dist/rollup.js:16854:16)
tiny-slider |     at Module.setSource (/tmp/node_modules/rollup/dist/rollup.js:16919:33)
tiny-slider |     at /tmp/node_modules/rollup/dist/rollup.js:20708:20
tiny-slider |     at <anonymous>
tiny-slider |     at process._tickCallback (internal/process/next_tick.js:188:7)
tiny-slider | [12:01:56] Finished 'makeDevCopy' after 153 ms
`
Does anyone know how to get the processed files (which should be in the dist folder) for this feature:
https://github.com/ganlanyuan/tiny-slider/pull/419/commits/742eade2186d24c9a20ed9cd88ee621ee57dc846

Thank you for any help, i am so confused by these endless wrappers ... It is so unclear for me, what steps need to be done to work on code which is embedded into all those other dev tools environments or how to call it.

best!

**Comment by dijkermans** [comment]
@ganlanyuan lazyLoadEager would be really great because swiping or mousedragging stops loading new items until you release the mouse or until you stop swiping. You'll see blank items and empty ALT tag boxes.

**Comment by dijkermans** [comment]
@baesek Hi do you have the compiled dist version? Would be great if you could share it so I could use the feature.

**Comment by dijkermans** [comment]
@sun-ks Works great! A slight improvement request though: If you set different values for different breakpoints then the value needs to be updated if you change the size of the viewport.

    responsive: {
      0: {
        items: 1,
	loadPrevNext:1,
      },
      580: {
        items: 2,
	loadPrevNext:2,		
      },
      1200: {
        items: 3,
	loadPrevNext:3,				
      },
      2000: {
        items: 4,
	loadPrevNext:4,				
      }

So let's say the viewport size is 1920px it uses LoadPrevNext 3. But if you change it to 480px then it's still 3. If you refresh the page then it uses value 1.

**Comment by mattmortek** [comment]
If anyone is looking for a working solution for this problem, please use this fork: https://github.com/b2storefront/tiny-slider

**Pull request closed without merging**
